### ISSUE TITLE
docs doesn't match with 3.7.0 release notes

### ISSUE THREAD

**Issue by vishiy** [helm/helm-www#1203] opened 2021-09-21 06:02 UTC
3.7.0 release notes says helm chart save is removed, but helm 3.7.0 registries doc says otherwise (https://helm.sh/docs/topics/registries/). Can someone please point to docs on how does one work with registries with 3.7.0 , as chart export and chart save has been removed as per release notes? Thanks.

**Comment by hickeyma** [comment] 2021-09-21 11:56
Duplicate of #1196

**Comment by hickeyma** [comment] 2021-09-21 11:56
Closing as its a duplicate

**Closed by hickeyma** 2021-09-21 11:56 UTC
