### ISSUE TITLE
Code examples unreadable due to contrast

### ISSUE THREAD

**Issue by edhgoose** [helm/helm-www#522] opened 2020-03-02 23:42 UTC
I'm looking at https://helm.sh/docs/topics/charts/, and this is what I can see:

<img width="1399" alt="Helm___Charts" src="https://user-images.githubusercontent.com/1108173/75728140-e0aab380-5cde-11ea-9b82-33f1cc85ff48.png">

It's nearly totally unusable I'm afraid.

It seems to be the same on any page with the `<code>` blocks. E.g. here's a screenshot from https://helm.sh/docs/intro/using_helm/

<img width="945" alt="Helm___Using_Helm" src="https://user-images.githubusercontent.com/1108173/75728333-5c0c6500-5cdf-11ea-8e9d-c014a465f482.png">

I'm using Chrome/80.0.3987.122.

**Comment by flynnduism** [comment] 2020-03-03 00:28
Duplicate of #499. 

Investigating this - the markup on the site shows a code highlighter being applied to these sections, overwriting the site CSS and dropping inline styles directly into the code examples. 

![Screen Shot 2020-03-02 at 4 26 29 PM](https://user-images.githubusercontent.com/686194/75730811-ba672280-5ca2-11ea-8c00-9b317574cd05.png)

I'm not sure where this is coming from, I will apply a fix asap.

**Comment by bacongobbler** [comment] 2020-03-03 05:17
Fixed in #523

**Closed by bacongobbler** 2020-03-03 05:17 UTC
