### ISSUE TITLE
broken link in documentation

### ISSUE THREAD

**Issue by drewandersen** [helm/helm-www#157] opened 2018-11-19 16:50 UTC
Link: https://docs.helm.sh/using_helm/rbac

Referenced from: https://docs.helm.sh/using_helm/#special-note-for-rbac-users

![image](https://user-images.githubusercontent.com/2484277/48722069-1a0afd00-ec1b-11e8-8aa9-e6dacdb2113e.png)

**Comment by bridgetkromhout** [comment] 2018-11-21 00:15
Any links whose rewrites are happening in https://github.com/helm/helm-www/blob/master/docs.helm.sh/gulpfile.js#L245-L271 are going to have a problem starting from https://docs.helm.sh/using_helm without a trailing slash, because:

-  instead of being rewritten correctly - like the link from `To apply configurations that secure Helm for use in production environments and other multi-tenant scenarios, see Securing a Helm installation` which should go from https://docs.helm.sh/using_helm/#securing-your-helm-installation to where the content is rewritten with ` .pipe(replace('securing_installation', 'securing-your-helm-installation'))` to be served from https://github.com/helm/helm/blob/master/docs/securing_installation.md

- they'll be read incorrectly as https://docs.helm.sh/#securing-your-helm-installation which doesn't point to anything.

(I haven't investigated every possible case, but this is definitely reproducible in several of the cases in that rewrites list.)

**Comment by farrellit** [comment] 2018-12-10 20:22
Is that also why some of the in-text links here don't work too?  Screenshot didn'tcapture the mouse but I'm hovering over the underscored "helm repo" link.    In the nav bar the underscores are `-` instead and that works (second image). 

![image](https://user-images.githubusercontent.com/6018542/49759254-c40fff00-fc86-11e8-8499-8096c67fa78d.png)

![image](https://user-images.githubusercontent.com/6018542/49759325-f7eb2480-fc86-11e8-8ed4-a12482a36ca3.png)

**Comment by bacongobbler** [comment] 2019-01-08 19:43
closed via #168

**Closed by bacongobbler** 2019-01-08 19:43 UTC
Labels: bug
