### ISSUE TITLE
cannot get package helm.sh/helm/v3/*

### ISSUE THREAD

**Issue by OojaxoO** [helm/helm-www#552] opened 2020-03-31 09:41 UTC
package helm.sh/helm/v3/internal/experimental/registry: unrecognized import path "helm.sh/helm/v3/internal/experimental/registry" (parse https://helm.sh/helm/v3/internal/experimental/registry?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/chart: unrecognized import path "helm.sh/helm/v3/pkg/chart" (parse https://helm.sh/helm/v3/pkg/chart?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/chart/loader: unrecognized import path "helm.sh/helm/v3/pkg/chart/loader" (parse https://helm.sh/helm/v3/pkg/chart/loader?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/chartutil: unrecognized import path "helm.sh/helm/v3/pkg/chartutil" (parse https://helm.sh/helm/v3/pkg/chartutil?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/cli: unrecognized import path "helm.sh/helm/v3/pkg/cli" (parse https://helm.sh/helm/v3/pkg/cli?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/downloader: unrecognized import path "helm.sh/helm/v3/pkg/downloader" (parse https://helm.sh/helm/v3/pkg/downloader?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/engine: unrecognized import path "helm.sh/helm/v3/pkg/engine" (parse https://helm.sh/helm/v3/pkg/engine?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/getter: unrecognized import path "helm.sh/helm/v3/pkg/getter" (parse https://helm.sh/helm/v3/pkg/getter?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/kube: unrecognized import path "helm.sh/helm/v3/pkg/kube" (parse https://helm.sh/helm/v3/pkg/kube?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/kube/fake: unrecognized import path "helm.sh/helm/v3/pkg/kube/fake" (parse https://helm.sh/helm/v3/pkg/kube/fake?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/lint: unrecognized import path "helm.sh/helm/v3/pkg/lint" (parse https://helm.sh/helm/v3/pkg/lint?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/lint/support: unrecognized import path "helm.sh/helm/v3/pkg/lint/support" (parse https://helm.sh/helm/v3/pkg/lint/support?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/postrender: unrecognized import path "helm.sh/helm/v3/pkg/postrender" (parse https://helm.sh/helm/v3/pkg/postrender?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/provenance: unrecognized import path "helm.sh/helm/v3/pkg/provenance" (parse https://helm.sh/helm/v3/pkg/provenance?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/release: unrecognized import path "helm.sh/helm/v3/pkg/release" (parse https://helm.sh/helm/v3/pkg/release?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/releaseutil: unrecognized import path "helm.sh/helm/v3/pkg/releaseutil" (parse https://helm.sh/helm/v3/pkg/releaseutil?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/repo: unrecognized import path "helm.sh/helm/v3/pkg/repo" (parse https://helm.sh/helm/v3/pkg/repo?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/storage: unrecognized import path "helm.sh/helm/v3/pkg/storage" (parse https://helm.sh/helm/v3/pkg/storage?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/storage/driver: unrecognized import path "helm.sh/helm/v3/pkg/storage/driver" (parse https://helm.sh/helm/v3/pkg/storage/driver?go-get=1: no go-import meta tags ())
package helm.sh/helm/v3/pkg/time: unrecognized import path "helm.sh/helm/v3/pkg/time" (parse https://helm.sh/helm/v3/pkg/time?go-get=1: no go-import meta tags ())

**Comment by hickeyma** [comment] 2020-03-31 10:54
@OojaxoO Can you describe this issue better so we can help you? Also, do you mean to raise it against documentation?

**Comment by hickeyma** [comment] 2020-03-31 10:57
Duplicate of https://github.com/helm/helm/issues/7842

**Comment by hickeyma** [comment] 2020-03-31 10:57
Closing as this seems to be a duplicate of https://github.com/helm/helm/issues/7842

**Closed by hickeyma** 2020-03-31 10:57 UTC
