### ISSUE TITLE
Add winget install to Documentation

### ISSUE THREAD

**Issue by MaxKlotz** [helm/helm-www#1471] opened 2023-05-16 12:04 UTC
It is possible to install helm via winget, but it is not mentioned in the [documentation](https://helm.sh/docs/intro/install/).
![grafik](https://github.com/helm/helm-www/assets/18208732/1e23d345-a66c-41ea-b101-25562f7dd3ec)

Please add this to the documentation.

**Comment by yxxhero** [comment] 2023-05-16 12:55
@MaxKlotz is still maintained now?

**Comment by MaxKlotz** [comment] 2023-05-16 13:19
The current version 3.12.0 is not yet released, but version 3.11.3 was released to winget.
The last discussion I found in the helm repo was under [this issue](https://github.com/helm/helm/issues/8203).
It reads as "resolved". I haven't found an issue in this repo.

**Comment by Ubunfu** [comment] 2023-05-24 20:19
I've followed the trail of bread crumbs across the internet to this thread lol.  `winget install Helm.Helm` from powershell seems to have taken care of the installation, but does anyone know how to invoke this thing?  Every permutation of the command name and package ID I can think of returns the "command not found" error message from powershell.  Even after re-opening the shell, running as admin, etc.

**Comment by Ubunfu** [comment] 2023-05-24 20:38
I'm kind of just making an educated guess here, but I think the $PATH entry that gets set when you install the package with winget might just be incomplete. 

It looks like when I installed the package, winget added an entry to my user-level $PATH envar is this: `C:\Users\ME\AppData\Local\Microsoft\WinGet\Packages\Helm.Helm_Microsoft.Winget.Source_8wekyb3d8bbwe`.  But if I inspect that path in powershell, I see that the `helm.exe` binary is actually buried one level deeper, in `windows-amd64/`.  If you just append that extra bit on to the path entry, click OK to close all the menus, and reopen powershell, just running `helm` works like you'd expect.

**Comment by MaxKlotz** [comment] 2023-05-30 13:34
Hi @Ubunfu
I think your Problem will be better placed [here](https://github.com/helm/helm) because it is a problem regarding the functionality and not documentation.
Maybe link to [this issue](https://github.com/helm/helm/issues/8203). The last message there was that "it seems to work".
I will definitely upvote your issue ;)

**Comment by Ubunfu** [comment] 2023-06-01 01:27
Good point, thanks.  Searching through the existing issues there, I see this guy already reported [exactly the same thing](https://github.com/helm/helm/issues/11885), but closed it as a duplicate of this [msft/winget-packages issue](https://github.com/microsoft/winget-pkgs/issues/96973), which apparently root-caused to a problem with the winget CLI not honoring some sort of winget package config?  I haven't verified but a few people over there seem to agree.  🤷

**Comment by ramnar-oss** [comment] 2023-08-06 16:26
@yxxhero @MaxKlotz  - I would like to create PR to update documentation for installation of helm using winget

**Closed** 2024-04-18 14:07 UTC
