### ISSUE TITLE
Helm commands missing from v3 docs

### ISSUE THREAD

**Issue by Datamance** [helm/helm-www#383] opened 2019-11-13 22:02 UTC
![image](https://user-images.githubusercontent.com/8699411/68808151-2449b680-0637-11ea-8995-f4051eab8864.png)

Not a big deal since the 2.x docs have them, although there were a few changes mentioned in the new FAQ.

**Comment by bacongobbler** [comment] 2019-11-13 22:11
Hi @Datamance. The section containing CLI help text output was removed from the documentation for Helm 3. We did this to ease the process of contributing new documentation to the site.

You can view these documents locally with the `helm docs` command.

Closing as a duplicate of https://github.com/helm/helm/issues/6877. Thanks!

**Closed by bacongobbler** 2019-11-13 22:11 UTC

**Comment by Datamance** [comment] 2019-11-19 18:05
@bacongobbler `helm docs` gives me nothing on the command line (this is for version 3.0.0). Furthermore, `helm help` doesn't list `docs` as an option.

here's my version info:
```helm version                                                                                                 Tue Nov 19 13:03:11 2019
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Comment by bacongobbler** [comment] 2019-11-19 18:22
It's a hidden command, but it should be there. 

https://github.com/helm/helm/blob/master/cmd/helm/root.go#L398-L399
https://github.com/helm/helm/blob/master/cmd/helm/docs.go#L53
